name: medibot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9  # ✅ 최신 버전 확인
  intl: ^0.18.0
  location: ^5.0.3
  flutter_keyboard_visibility: ^6.0.0
  http: ^1.3.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  # google_ml_kit: ^0.13.0
  image_picker: ^1.0.4
  flutter_typeahead: ^5.2.0 # 자동완성 검색 UI
  kakao_map_plugin: ^0.3.5     # flutter_tesseract_ocr: ^0.3.3
  geolocator: ^10.1.0
  android_intent_plus: ^5.3.0
  fl_chart: ^0.64.0
  flutter_launcher_icons: ^0.13.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_local_notifications: 14.1.1
  timezone: ^0.9.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/morning_bg.jpg
    - assets/evening_bg.jpg
    - assets/mediIcon.jpg
    - assets/Icon.jpg
    - assets/pill.png
    - assets/logo.png
    - assets/register.png
    - assets/pharmacy.png
    - assets/search.png
    - assets/analysis.png
    - assets/cal.png
    - assets/logo_face_white.png


flutter_icons:
  android: true
  ios: true 
  image_path: "assets/logo.png"
